### ISSUE TITLE
Implement Godeps or vendoring

### ISSUE THREAD

**Issue by Raffo** [zalando-techmonkeys/gin-gomonitor#3]
Every project build must be reproducible and we need to support Godep or to vendor the current dependencies.

**Comment by szuecs** [comment]
I would add glide.

**Comment by mikkeloscar** [comment]
It's best to avoid vendoring dependencies in a library because otherwise people will not be able to use the library unless they also vendor the same dependencies in their own project.

**Comment by szuecs** [comment]
I think you are right @mikkeloscar . Thanks for your suggestion.
