### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando-techmonkeys/gin-gomonitor#4]
Hey guys -- looks like this has been a bit dormant on the development front. Will you build it out further? You've promoted this + the two other gin middleware projects via golang nuts ... any response? The READMEs for the three projects are a bit skeletal ... I think adding more info as per my doc checklist/template could help. Thoughts?

**Comment by szuecs** [comment]
Thanks, that would be awesome.
We got some responses and a PR. I did not write e-mails to go-nuts after publishing new versions. 
I always wanted to do it. :)

**Comment by szuecs** [comment]
This hackweek I work on it and I will add some features that will be enhance the project a lot.
